version: '3.7'

services:
  consul:
    image: consul
    ports:
      - "8500:8500"
    networks:
      - proiectchord
  chordnode:
    build:
      context: ../
      dockerfile: ./demo-network/Dockerfile
    networks:
      - proiectchord
    restart: always
    depends_on:
      - consul

networks:
  proiectchord:
    name: proiectchord
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.10.0/24