// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: chordpb/chordpb.proto

package chordpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Node struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Ip string `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
}

func (x *Node) Reset() {
	*x = Node{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chordpb_chordpb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_chordpb_chordpb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_chordpb_chordpb_proto_rawDescGZIP(), []int{0}
}

func (x *Node) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Node) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type Nil struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Nil) Reset() {
	*x = Nil{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chordpb_chordpb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Nil) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nil) ProtoMessage() {}

func (x *Nil) ProtoReflect() protoreflect.Message {
	mi := &file_chordpb_chordpb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nil.ProtoReflect.Descriptor instead.
func (*Nil) Descriptor() ([]byte, []int) {
	return file_chordpb_chordpb_proto_rawDescGZIP(), []int{1}
}

type UFTRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Node *Node `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Idx  int64 `protobuf:"varint,2,opt,name=idx,proto3" json:"idx,omitempty"`
}

func (x *UFTRequest) Reset() {
	*x = UFTRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chordpb_chordpb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UFTRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UFTRequest) ProtoMessage() {}

func (x *UFTRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chordpb_chordpb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UFTRequest.ProtoReflect.Descriptor instead.
func (*UFTRequest) Descriptor() ([]byte, []int) {
	return file_chordpb_chordpb_proto_rawDescGZIP(), []int{2}
}

func (x *UFTRequest) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *UFTRequest) GetIdx() int64 {
	if x != nil {
		return x.Idx
	}
	return 0
}

type Id struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Id) Reset() {
	*x = Id{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chordpb_chordpb_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Id) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Id) ProtoMessage() {}

func (x *Id) ProtoReflect() protoreflect.Message {
	mi := &file_chordpb_chordpb_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Id.ProtoReflect.Descriptor instead.
func (*Id) Descriptor() ([]byte, []int) {
	return file_chordpb_chordpb_proto_rawDescGZIP(), []int{3}
}

func (x *Id) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chordpb_chordpb_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chordpb_chordpb_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_chordpb_chordpb_proto_rawDescGZIP(), []int{4}
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *GetReply) Reset() {
	*x = GetReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chordpb_chordpb_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReply) ProtoMessage() {}

func (x *GetReply) ProtoReflect() protoreflect.Message {
	mi := &file_chordpb_chordpb_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReply.ProtoReflect.Descriptor instead.
func (*GetReply) Descriptor() ([]byte, []int) {
	return file_chordpb_chordpb_proto_rawDescGZIP(), []int{5}
}

func (x *GetReply) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type StoreRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *StoreRequest) Reset() {
	*x = StoreRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chordpb_chordpb_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreRequest) ProtoMessage() {}

func (x *StoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chordpb_chordpb_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreRequest.ProtoReflect.Descriptor instead.
func (*StoreRequest) Descriptor() ([]byte, []int) {
	return file_chordpb_chordpb_proto_rawDescGZIP(), []int{6}
}

func (x *StoreRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *StoreRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type GetFileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *GetFileRequest) Reset() {
	*x = GetFileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chordpb_chordpb_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileRequest) ProtoMessage() {}

func (x *GetFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chordpb_chordpb_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileRequest.ProtoReflect.Descriptor instead.
func (*GetFileRequest) Descriptor() ([]byte, []int) {
	return file_chordpb_chordpb_proto_rawDescGZIP(), []int{7}
}

func (x *GetFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type GetFileReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetFileReply) Reset() {
	*x = GetFileReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chordpb_chordpb_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFileReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileReply) ProtoMessage() {}

func (x *GetFileReply) ProtoReflect() protoreflect.Message {
	mi := &file_chordpb_chordpb_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileReply.ProtoReflect.Descriptor instead.
func (*GetFileReply) Descriptor() ([]byte, []int) {
	return file_chordpb_chordpb_proto_rawDescGZIP(), []int{8}
}

func (x *GetFileReply) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type StoreFileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *StoreFileRequest) Reset() {
	*x = StoreFileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chordpb_chordpb_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreFileRequest) ProtoMessage() {}

func (x *StoreFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chordpb_chordpb_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreFileRequest.ProtoReflect.Descriptor instead.
func (*StoreFileRequest) Descriptor() ([]byte, []int) {
	return file_chordpb_chordpb_proto_rawDescGZIP(), []int{9}
}

func (x *StoreFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *StoreFileRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_chordpb_chordpb_proto protoreflect.FileDescriptor

var file_chordpb_chordpb_proto_rawDesc = []byte{
	0x0a, 0x15, 0x63, 0x68, 0x6f, 0x72, 0x64, 0x70, 0x62, 0x2f, 0x63, 0x68, 0x6f, 0x72, 0x64, 0x70,
	0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x63, 0x68, 0x6f, 0x72, 0x64, 0x70, 0x62,
	0x22, 0x26, 0x0a, 0x04, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x22, 0x05, 0x0a, 0x03, 0x4e, 0x69, 0x6c, 0x22,
	0x41, 0x0a, 0x0a, 0x55, 0x46, 0x54, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a,
	0x04, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x63, 0x68,
	0x6f, 0x72, 0x64, 0x70, 0x62, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x6e, 0x6f, 0x64, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x69,
	0x64, 0x78, 0x22, 0x14, 0x0a, 0x02, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x1e, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x20, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x36, 0x0a, 0x0c, 0x53, 0x74,
	0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x22, 0x24, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x22, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x46,
	0x69, 0x6c, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x3a, 0x0a, 0x10,
	0x53, 0x74, 0x6f, 0x72, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x70, 0x61, 0x74, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0x85, 0x05, 0x0a, 0x0c, 0x43, 0x68, 0x6f,
	0x72, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2b, 0x0a, 0x0d, 0x46, 0x69, 0x6e,
	0x64, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x12, 0x0b, 0x2e, 0x63, 0x68, 0x6f,
	0x72, 0x64, 0x70, 0x62, 0x2e, 0x49, 0x64, 0x1a, 0x0d, 0x2e, 0x63, 0x68, 0x6f, 0x72, 0x64, 0x70,
	0x62, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x2d, 0x0a, 0x0f, 0x46, 0x69, 0x6e, 0x64, 0x50, 0x72,
	0x65, 0x64, 0x65, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x12, 0x0b, 0x2e, 0x63, 0x68, 0x6f, 0x72,
	0x64, 0x70, 0x62, 0x2e, 0x49, 0x64, 0x1a, 0x0d, 0x2e, 0x63, 0x68, 0x6f, 0x72, 0x64, 0x70, 0x62,
	0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x34, 0x0a, 0x16, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x73, 0x74,
	0x50, 0x72, 0x65, 0x63, 0x65, 0x64, 0x69, 0x6e, 0x67, 0x46, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x12,
	0x0b, 0x2e, 0x63, 0x68, 0x6f, 0x72, 0x64, 0x70, 0x62, 0x2e, 0x49, 0x64, 0x1a, 0x0d, 0x2e, 0x63,
	0x68, 0x6f, 0x72, 0x64, 0x70, 0x62, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x25, 0x0a, 0x06, 0x4e,
	0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x0d, 0x2e, 0x63, 0x68, 0x6f, 0x72, 0x64, 0x70, 0x62, 0x2e,
	0x4e, 0x6f, 0x64, 0x65, 0x1a, 0x0c, 0x2e, 0x63, 0x68, 0x6f, 0x72, 0x64, 0x70, 0x62, 0x2e, 0x4e,
	0x69, 0x6c, 0x12, 0x36, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x69, 0x6e, 0x67,
	0x65, 0x72, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x13, 0x2e, 0x63, 0x68, 0x6f, 0x72, 0x64, 0x70,
	0x62, 0x2e, 0x55, 0x46, 0x54, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0c, 0x2e, 0x63,
	0x68, 0x6f, 0x72, 0x64, 0x70, 0x62, 0x2e, 0x4e, 0x69, 0x6c, 0x12, 0x2b, 0x0a, 0x0c, 0x47, 0x65,
	0x74, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x12, 0x0c, 0x2e, 0x63, 0x68, 0x6f,
	0x72, 0x64, 0x70, 0x62, 0x2e, 0x4e, 0x69, 0x6c, 0x1a, 0x0d, 0x2e, 0x63, 0x68, 0x6f, 0x72, 0x64,
	0x70, 0x62, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x2d, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x50, 0x72,
	0x65, 0x64, 0x65, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x12, 0x0c, 0x2e, 0x63, 0x68, 0x6f, 0x72,
	0x64, 0x70, 0x62, 0x2e, 0x4e, 0x69, 0x6c, 0x1a, 0x0d, 0x2e, 0x63, 0x68, 0x6f, 0x72, 0x64, 0x70,
	0x62, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x2b, 0x0a, 0x0c, 0x53, 0x65, 0x74, 0x53, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x12, 0x0d, 0x2e, 0x63, 0x68, 0x6f, 0x72, 0x64, 0x70, 0x62,
	0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x1a, 0x0c, 0x2e, 0x63, 0x68, 0x6f, 0x72, 0x64, 0x70, 0x62, 0x2e,
	0x4e, 0x69, 0x6c, 0x12, 0x2d, 0x0a, 0x0e, 0x53, 0x65, 0x74, 0x50, 0x72, 0x65, 0x64, 0x65, 0x63,
	0x65, 0x73, 0x73, 0x6f, 0x72, 0x12, 0x0d, 0x2e, 0x63, 0x68, 0x6f, 0x72, 0x64, 0x70, 0x62, 0x2e,
	0x4e, 0x6f, 0x64, 0x65, 0x1a, 0x0c, 0x2e, 0x63, 0x68, 0x6f, 0x72, 0x64, 0x70, 0x62, 0x2e, 0x4e,
	0x69, 0x6c, 0x12, 0x2d, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x13, 0x2e, 0x63, 0x68, 0x6f, 0x72,
	0x64, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11,
	0x2e, 0x63, 0x68, 0x6f, 0x72, 0x64, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x2c, 0x0a, 0x05, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x12, 0x15, 0x2e, 0x63, 0x68, 0x6f,
	0x72, 0x64, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x0c, 0x2e, 0x63, 0x68, 0x6f, 0x72, 0x64, 0x70, 0x62, 0x2e, 0x4e, 0x69, 0x6c, 0x12,
	0x39, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x17, 0x2e, 0x63, 0x68, 0x6f,
	0x72, 0x64, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x63, 0x68, 0x6f, 0x72, 0x64, 0x70, 0x62, 0x2e, 0x47, 0x65,
	0x74, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x34, 0x0a, 0x09, 0x53, 0x74,
	0x6f, 0x72, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x19, 0x2e, 0x63, 0x68, 0x6f, 0x72, 0x64, 0x70,
	0x62, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x0c, 0x2e, 0x63, 0x68, 0x6f, 0x72, 0x64, 0x70, 0x62, 0x2e, 0x4e, 0x69, 0x6c,
	0x42, 0x27, 0x5a, 0x25, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61,
	0x64, 0x72, 0x67, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x69, 0x65, 0x63, 0x74, 0x63, 0x68, 0x6f, 0x72,
	0x64, 0x2f, 0x63, 0x68, 0x6f, 0x72, 0x64, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_chordpb_chordpb_proto_rawDescOnce sync.Once
	file_chordpb_chordpb_proto_rawDescData = file_chordpb_chordpb_proto_rawDesc
)

func file_chordpb_chordpb_proto_rawDescGZIP() []byte {
	file_chordpb_chordpb_proto_rawDescOnce.Do(func() {
		file_chordpb_chordpb_proto_rawDescData = protoimpl.X.CompressGZIP(file_chordpb_chordpb_proto_rawDescData)
	})
	return file_chordpb_chordpb_proto_rawDescData
}

var file_chordpb_chordpb_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_chordpb_chordpb_proto_goTypes = []interface{}{
	(*Node)(nil),             // 0: chordpb.Node
	(*Nil)(nil),              // 1: chordpb.Nil
	(*UFTRequest)(nil),       // 2: chordpb.UFTRequest
	(*Id)(nil),               // 3: chordpb.Id
	(*GetRequest)(nil),       // 4: chordpb.GetRequest
	(*GetReply)(nil),         // 5: chordpb.GetReply
	(*StoreRequest)(nil),     // 6: chordpb.StoreRequest
	(*GetFileRequest)(nil),   // 7: chordpb.GetFileRequest
	(*GetFileReply)(nil),     // 8: chordpb.GetFileReply
	(*StoreFileRequest)(nil), // 9: chordpb.StoreFileRequest
}
var file_chordpb_chordpb_proto_depIdxs = []int32{
	0,  // 0: chordpb.UFTRequest.node:type_name -> chordpb.Node
	3,  // 1: chordpb.ChordService.FindSuccessor:input_type -> chordpb.Id
	3,  // 2: chordpb.ChordService.FindPredecessor:input_type -> chordpb.Id
	3,  // 3: chordpb.ChordService.ClosestPrecedingFinger:input_type -> chordpb.Id
	0,  // 4: chordpb.ChordService.Notify:input_type -> chordpb.Node
	2,  // 5: chordpb.ChordService.UpdateFingerTable:input_type -> chordpb.UFTRequest
	1,  // 6: chordpb.ChordService.GetSuccessor:input_type -> chordpb.Nil
	1,  // 7: chordpb.ChordService.GetPredecessor:input_type -> chordpb.Nil
	0,  // 8: chordpb.ChordService.SetSuccessor:input_type -> chordpb.Node
	0,  // 9: chordpb.ChordService.SetPredecessor:input_type -> chordpb.Node
	4,  // 10: chordpb.ChordService.Get:input_type -> chordpb.GetRequest
	6,  // 11: chordpb.ChordService.Store:input_type -> chordpb.StoreRequest
	7,  // 12: chordpb.ChordService.GetFile:input_type -> chordpb.GetFileRequest
	9,  // 13: chordpb.ChordService.StoreFile:input_type -> chordpb.StoreFileRequest
	0,  // 14: chordpb.ChordService.FindSuccessor:output_type -> chordpb.Node
	0,  // 15: chordpb.ChordService.FindPredecessor:output_type -> chordpb.Node
	0,  // 16: chordpb.ChordService.ClosestPrecedingFinger:output_type -> chordpb.Node
	1,  // 17: chordpb.ChordService.Notify:output_type -> chordpb.Nil
	1,  // 18: chordpb.ChordService.UpdateFingerTable:output_type -> chordpb.Nil
	0,  // 19: chordpb.ChordService.GetSuccessor:output_type -> chordpb.Node
	0,  // 20: chordpb.ChordService.GetPredecessor:output_type -> chordpb.Node
	1,  // 21: chordpb.ChordService.SetSuccessor:output_type -> chordpb.Nil
	1,  // 22: chordpb.ChordService.SetPredecessor:output_type -> chordpb.Nil
	5,  // 23: chordpb.ChordService.Get:output_type -> chordpb.GetReply
	1,  // 24: chordpb.ChordService.Store:output_type -> chordpb.Nil
	8,  // 25: chordpb.ChordService.GetFile:output_type -> chordpb.GetFileReply
	1,  // 26: chordpb.ChordService.StoreFile:output_type -> chordpb.Nil
	14, // [14:27] is the sub-list for method output_type
	1,  // [1:14] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_chordpb_chordpb_proto_init() }
func file_chordpb_chordpb_proto_init() {
	if File_chordpb_chordpb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_chordpb_chordpb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Node); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chordpb_chordpb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Nil); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chordpb_chordpb_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UFTRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chordpb_chordpb_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Id); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chordpb_chordpb_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chordpb_chordpb_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chordpb_chordpb_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chordpb_chordpb_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chordpb_chordpb_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFileReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chordpb_chordpb_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreFileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_chordpb_chordpb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chordpb_chordpb_proto_goTypes,
		DependencyIndexes: file_chordpb_chordpb_proto_depIdxs,
		MessageInfos:      file_chordpb_chordpb_proto_msgTypes,
	}.Build()
	File_chordpb_chordpb_proto = out.File
	file_chordpb_chordpb_proto_rawDesc = nil
	file_chordpb_chordpb_proto_goTypes = nil
	file_chordpb_chordpb_proto_depIdxs = nil
}
